name: Formatters & Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project (pull-request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2.3.2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout project (main)
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      - name: Label PR
        if: github.event_name == 'pull_request'
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Setup yq
        run: sudo snap install yq
      - name: Run pre-conditions
        run: test -f .github/actions.yml && eval "$(yq e '.pre.ci // "true"' .github/actions.yml)" || true
      - name: Run checks
        run: sbt test
      - name: Run post-conditions
        run: test -f .github/actions.yml && eval "$(yq e '.post.ci // "true"' .github/actions.yml)" || true